name: TidyFinder
options:
  bundleIdPrefix: com.scottdix
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  groupSortPosition: top
packages:
  TidyFinderCore:
    path: ..
settings:
  PRODUCT_BUNDLE_IDENTIFIER: com.scottdix.TidyFinder
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  DEVELOPMENT_TEAM: ""
  CODE_SIGN_STYLE: Automatic
  SWIFT_VERSION: 5.9
  MACOSX_DEPLOYMENT_TARGET: 13.0
  ENABLE_HARDENED_RUNTIME: YES
  ENABLE_APP_SANDBOX: YES
targets:
  TidyFinder:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Sources/TidyFinder
    resources:
      - Resources
    dependencies:
      - package: TidyFinderCore
        product: TidyFinderCore
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: TidyFinder
        CFBundleName: TidyFinder
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        NSHighResolutionCapable: true
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication
        LSApplicationCategoryType: public.app-category.utilities
    entitlements:
      path: Resources/TidyFinder.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.scottdix.TidyFinder
      INFOPLIST_FILE: Resources/Info.plist
      CODE_SIGN_ENTITLEMENTS: Resources/TidyFinder.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_VERSION: 5.9
      MACOSX_DEPLOYMENT_TARGET: 13.0
  TidyFinderTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Tests/TidyFinderTests
    dependencies:
      - target: TidyFinder
        link: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.scottdix.TidyFinderTests
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/TidyFinder.app/Contents/MacOS/TidyFinder
      SWIFT_VERSION: 5.9
      MACOSX_DEPLOYMENT_TARGET: 13.0
